version: '2.1'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    build:
      context: .
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - ${PWD}/etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg
      - ${PWD}/etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg
      - ${PWD}/ca.key.pem:/etc/pki/CA/private/ca.key.pem
      - ${PWD}/ca.cert.pem:/etc/pki/CA/certs/ca.cert.pem
    restart: always
    network_mode: "host"
